# Generated by Django 5.2.5 on 2025-08-30 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science & Engineering"),
                            ("ECE", "Electronics & Communication Engineering"),
                            ("EE", "Electrical Engineering"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science & Engineering"),
                            ("ECE", "Electronics & Communication Engineering"),
                            ("EE", "Electrical Engineering"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=20, unique=True)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science & Engineering"),
                            ("ECE", "Electronics & Communication Engineering"),
                            ("EE", "Electrical Engineering"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.batch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batch",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="timetable.subject"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="timetable.teacher"
            ),
        ),
    ]
